import re

new_foods = """import type { FoodItem } from '@/types'

export const FOODS: FoodItem[] = [
  // NIGERIAN PROTEINS
  { id: 1,   name: 'Moi Moi (1 piece)',              category: 'protein', kcal: 160, protein: 9,  carbs: 18, fat: 5  },
  { id: 2,   name: 'Akara (1 piece)',                category: 'protein', kcal: 110, protein: 5,  carbs: 12, fat: 5  },
  { id: 3,   name: 'Boiled Egg',                     category: 'protein', kcal: 78,  protein: 6,  carbs: 1,  fat: 5  },
  { id: 4,   name: 'Boiled Eggs (2)',                category: 'protein', kcal: 156, protein: 12, carbs: 2,  fat: 10 },
  { id: 5,   name: 'Grilled Chicken (100g)',          category: 'protein', kcal: 165, protein: 31, carbs: 0,  fat: 4  },
  { id: 6,   name: 'Fried Chicken (1 piece)',         category: 'protein', kcal: 320, protein: 28, carbs: 12, fat: 18 },
  { id: 7,   name: 'Chicken Drumstick (grilled)',    category: 'protein', kcal: 185, protein: 27, carbs: 0,  fat: 8  },
  { id: 8,   name: 'Grilled Fish / Tilapia (100g)',  category: 'protein', kcal: 128, protein: 26, carbs: 0,  fat: 3  },
  { id: 9,   name: 'Fried Fish (100g)',              category: 'protein', kcal: 210, protein: 22, carbs: 5,  fat: 12 },
  { id: 10,  name: 'Catfish (100g)',                 category: 'protein', kcal: 105, protein: 18, carbs: 0,  fat: 3  },
  { id: 11,  name: 'Goat Meat (100g)',               category: 'protein', kcal: 143, protein: 27, carbs: 0,  fat: 3  },
  { id: 12,  name: 'Beef (100g)',                    category: 'protein', kcal: 250, protein: 26, carbs: 0,  fat: 16 },
  { id: 13,  name: 'Stockfish (50g)',                category: 'protein', kcal: 80,  protein: 17, carbs: 0,  fat: 1  },
  { id: 14,  name: 'Smoked Mackerel (100g)',         category: 'protein', kcal: 205, protein: 19, carbs: 0,  fat: 14 },
  { id: 15,  name: 'Suya (100g)',                    category: 'protein', kcal: 230, protein: 28, carbs: 3,  fat: 12 },
  { id: 16,  name: 'Asun (100g)',                    category: 'protein', kcal: 260, protein: 25, carbs: 4,  fat: 16 },
  { id: 17,  name: 'Nkwobi (1 serving)',             category: 'protein', kcal: 380, protein: 30, carbs: 6,  fat: 26 },
  { id: 18,  name: 'Cow Leg / Kpomo (100g)',         category: 'protein', kcal: 120, protein: 20, carbs: 0,  fat: 4  },
  { id: 19,  name: 'Tuna (canned, 100g)',            category: 'protein', kcal: 116, protein: 26, carbs: 0,  fat: 1  },
  { id: 20,  name: 'Sardines (1 can)',               category: 'protein', kcal: 190, protein: 22, carbs: 0,  fat: 11 },
  { id: 21,  name: 'Mackerel (canned, 100g)',        category: 'protein', kcal: 185, protein: 20, carbs: 0,  fat: 12 },
  { id: 22,  name: 'Prawns / Shrimp (100g)',         category: 'protein', kcal: 99,  protein: 24, carbs: 0,  fat: 1  },
  { id: 23,  name: 'Greek Yoghurt (100g)',           category: 'protein', kcal: 97,  protein: 9,  carbs: 6,  fat: 5  },
  { id: 24,  name: 'Puff Puff (1 piece)',            category: 'protein', kcal: 90,  protein: 2,  carbs: 12, fat: 4  },
  { id: 25,  name: 'Puff Puff (3 pieces)',           category: 'protein', kcal: 270, protein: 5,  carbs: 35, fat: 12 },

  // NIGERIAN CARBS
  { id: 50,  name: 'Jollof Rice (1 cup)',            category: 'carbs',   kcal: 380, protein: 7,  carbs: 68, fat: 10 },
  { id: 51,  name: 'Jollof Rice (half cup)',         category: 'carbs',   kcal: 190, protein: 4,  carbs: 34, fat: 5  },
  { id: 52,  name: 'Brown Rice (half cup cooked)',   category: 'carbs',   kcal: 110, protein: 3,  carbs: 23, fat: 1  },
  { id: 53,  name: 'Jollof Brown Rice (half cup)',   category: 'carbs',   kcal: 140, protein: 3,  carbs: 27, fat: 3  },
  { id: 54,  name: 'White Rice (1 cup cooked)',      category: 'carbs',   kcal: 206, protein: 4,  carbs: 45, fat: 0  },
  { id: 55,  name: 'Ofada Rice (half cup)',          category: 'carbs',   kcal: 115, protein: 3,  carbs: 24, fat: 1  },
  { id: 56,  name: 'Eba / Garri (small ball)',       category: 'carbs',   kcal: 180, protein: 2,  carbs: 42, fat: 0  },
  { id: 57,  name: 'Eba / Garri (medium ball)',      category: 'carbs',   kcal: 270, protein: 3,  carbs: 63, fat: 0  },
  { id: 58,  name: 'Fufu (small ball)',              category: 'carbs',   kcal: 160, protein: 1,  carbs: 38, fat: 0  },
  { id: 59,  name: 'Fufu (medium ball)',             category: 'carbs',   kcal: 280, protein: 2,  carbs: 66, fat: 0  },
  { id: 60,  name: 'Pounded Yam (small)',            category: 'carbs',   kcal: 200, protein: 2,  carbs: 47, fat: 0  },
  { id: 61,  name: 'Pounded Yam (medium)',           category: 'carbs',   kcal: 330, protein: 3,  carbs: 78, fat: 0  },
  { id: 62,  name: 'Amala (small)',                  category: 'carbs',   kcal: 160, protein: 2,  carbs: 38, fat: 0  },
  { id: 63,  name: 'Semolina (small)',               category: 'carbs',   kcal: 170, protein: 3,  carbs: 39, fat: 0  },
  { id: 64,  name: 'Tuwo Shinkafa (small)',          category: 'carbs',   kcal: 175, protein: 3,  carbs: 40, fat: 0  },
  { id: 65,  name: 'Boiled Yam (half cup)',          category: 'carbs',   kcal: 118, protein: 2,  carbs: 28, fat: 0  },
  { id: 66,  name: 'Fried Yam (100g)',               category: 'carbs',   kcal: 225, protein: 2,  carbs: 35, fat: 9  },
  { id: 67,  name: 'Boiled Plantain (1 finger)',     category: 'carbs',   kcal: 122, protein: 1,  carbs: 31, fat: 0  },
  { id: 68,  name: 'Roasted Plantain / Boli',        category: 'carbs',   kcal: 109, protein: 1,  carbs: 28, fat: 0  },
  { id: 69,  name: 'Fried Plantain (5 slices)',      category: 'carbs',   kcal: 220, protein: 1,  carbs: 38, fat: 8  },
  { id: 70,  name: 'Pap / Ogi (1 bowl)',             category: 'carbs',   kcal: 90,  protein: 2,  carbs: 20, fat: 1  },
  { id: 71,  name: 'Agege Bread (1 slice)',          category: 'carbs',   kcal: 110, protein: 3,  carbs: 21, fat: 2  },
  { id: 72,  name: 'Agege Bread (2 slices)',         category: 'carbs',   kcal: 220, protein: 6,  carbs: 42, fat: 4  },
  { id: 73,  name: 'White Bread (1 slice)',          category: 'carbs',   kcal: 79,  protein: 3,  carbs: 15, fat: 1  },
  { id: 74,  name: 'Brown Bread (1 slice)',          category: 'carbs',   kcal: 69,  protein: 3,  carbs: 13, fat: 1  },
  { id: 75,  name: 'Wholemeal Bread (1 slice)',      category: 'carbs',   kcal: 74,  protein: 4,  carbs: 14, fat: 1  },
  { id: 76,  name: 'Beans (1 cup cooked)',           category: 'carbs',   kcal: 227, protein: 15, carbs: 40, fat: 1  },
  { id: 77,  name: 'Beans (half cup cooked)',        category: 'carbs',   kcal: 113, protein: 8,  carbs: 20, fat: 0  },
  { id: 78,  name: 'Mashed Beans / Ewa Agoyin',     category: 'carbs',   kcal: 250, protein: 14, carbs: 42, fat: 5  },
  { id: 79,  name: 'Bread and Beans',               category: 'carbs',   kcal: 370, protein: 17, carbs: 62, fat: 6  },
  { id: 80,  name: 'Indomie Noodles (1 pack)',       category: 'carbs',   kcal: 375, protein: 8,  carbs: 52, fat: 14 },
  { id: 81,  name: 'Spaghetti (1 cup cooked)',       category: 'carbs',   kcal: 220, protein: 8,  carbs: 43, fat: 1  },
  { id: 82,  name: 'Oats (1 bowl)',                  category: 'carbs',   kcal: 150, protein: 5,  carbs: 27, fat: 3  },
  { id: 83,  name: 'Couscous (1 cup cooked)',        category: 'carbs',   kcal: 176, protein: 6,  carbs: 36, fat: 0  },
  { id: 84,  name: 'Sweet Potato (100g boiled)',     category: 'carbs',   kcal: 86,  protein: 2,  carbs: 20, fat: 0  },
  { id: 85,  name: 'Irish Potato (1 medium boiled)', category: 'carbs',   kcal: 130, protein: 3,  carbs: 30, fat: 0  },
  { id: 86,  name: 'Corn on the Cob (1 ear)',        category: 'carbs',   kcal: 132, protein: 5,  carbs: 29, fat: 2  },
  { id: 87,  name: 'Roasted Corn (1 ear)',           category: 'carbs',   kcal: 120, protein: 4,  carbs: 27, fat: 2  },

  // SOUPS AND STEWS
  { id: 100, name: 'Egusi Soup (1 ladle)',           category: 'veg',     kcal: 190, protein: 8,  carbs: 5,  fat: 15 },
  { id: 101, name: 'Egusi Soup (2 ladles)',          category: 'veg',     kcal: 380, protein: 16, carbs: 10, fat: 30 },
  { id: 102, name: 'Efo Riro (1 ladle)',             category: 'veg',     kcal: 120, protein: 5,  carbs: 6,  fat: 9  },
  { id: 103, name: 'Pepper Soup (1 bowl)',           category: 'veg',     kcal: 180, protein: 18, carbs: 4,  fat: 9  },
  { id: 104, name: 'Ogbono Soup (1 ladle)',          category: 'veg',     kcal: 200, protein: 8,  carbs: 4,  fat: 17 },
  { id: 105, name: 'Banga Soup (1 ladle)',           category: 'veg',     kcal: 220, protein: 6,  carbs: 6,  fat: 20 },
  { id: 106, name: 'Afang Soup (1 ladle)',           category: 'veg',     kcal: 170, protein: 10, carbs: 4,  fat: 13 },
  { id: 107, name: 'Vegetable Soup (1 ladle)',       category: 'veg',     kcal: 100, protein: 5,  carbs: 5,  fat: 7  },
  { id: 108, name: 'Ofe Onugbu (1 ladle)',           category: 'veg',     kcal: 150, protein: 7,  carbs: 4,  fat: 12 },
  { id: 109, name: 'Miyan Kuka (1 bowl)',            category: 'veg',     kcal: 110, protein: 5,  carbs: 6,  fat: 7  },
  { id: 110, name: 'Tomato Stew (2 tbsp)',           category: 'veg',     kcal: 80,  protein: 2,  carbs: 6,  fat: 6  },
  { id: 111, name: 'Ofada Stew (2 tbsp)',            category: 'veg',     kcal: 120, protein: 3,  carbs: 5,  fat: 10 },
  { id: 112, name: 'Okra Soup (1 ladle)',            category: 'veg',     kcal: 130, protein: 5,  carbs: 8,  fat: 9  },

  // SNACKS AND STREET FOOD
  { id: 130, name: 'Chin Chin (1 handful)',          category: 'snacks',  kcal: 180, protein: 3,  carbs: 25, fat: 8  },
  { id: 131, name: 'Biscuits (1 pack)',              category: 'snacks',  kcal: 150, protein: 2,  carbs: 22, fat: 6  },
  { id: 132, name: 'Plantain Chips (1 small bag)',   category: 'snacks',  kcal: 160, protein: 1,  carbs: 22, fat: 8  },
  { id: 133, name: 'Groundnuts / Peanuts (30g)',     category: 'snacks',  kcal: 170, protein: 7,  carbs: 5,  fat: 14 },
  { id: 134, name: 'Roasted Groundnuts (50g)',       category: 'snacks',  kcal: 280, protein: 12, carbs: 9,  fat: 23 },
  { id: 135, name: 'Coconut (1 piece)',              category: 'snacks',  kcal: 160, protein: 2,  carbs: 7,  fat: 15 },
  { id: 136, name: 'Cashew Nuts (30g)',              category: 'snacks',  kcal: 165, protein: 5,  carbs: 9,  fat: 13 },
  { id: 137, name: 'Banana (1 medium)',              category: 'snacks',  kcal: 89,  protein: 1,  carbs: 23, fat: 0  },
  { id: 138, name: 'Mango (1 medium)',               category: 'snacks',  kcal: 135, protein: 1,  carbs: 35, fat: 1  },
  { id: 139, name: 'Watermelon (1 slice)',           category: 'snacks',  kcal: 86,  protein: 2,  carbs: 22, fat: 0  },
  { id: 140, name: 'Orange (1 medium)',              category: 'snacks',  kcal: 62,  protein: 1,  carbs: 15, fat: 0  },
  { id: 141, name: 'Pawpaw / Papaya (1 slice)',      category: 'snacks',  kcal: 55,  protein: 1,  carbs: 14, fat: 0  },
  { id: 142, name: 'Pineapple (1 slice)',            category: 'snacks',  kcal: 50,  protein: 1,  carbs: 13, fat: 0  },
  { id: 143, name: 'Apple (1 medium)',               category: 'snacks',  kcal: 95,  protein: 0,  carbs: 25, fat: 0  },

  // DRINKS
  { id: 150, name: 'Zobo / Hibiscus Drink (1 cup)', category: 'drinks',  kcal: 30,  protein: 0,  carbs: 7,  fat: 0  },
  { id: 151, name: 'Kunu (1 cup)',                   category: 'drinks',  kcal: 80,  protein: 1,  carbs: 18, fat: 1  },
  { id: 152, name: 'Fura da Nono (1 cup)',           category: 'drinks',  kcal: 120, protein: 5,  carbs: 20, fat: 3  },
  { id: 153, name: 'Palm Wine (1 cup)',              category: 'drinks',  kcal: 90,  protein: 1,  carbs: 15, fat: 0  },
  { id: 154, name: 'Malta / Malt Drink (1 bottle)', category: 'drinks',  kcal: 150, protein: 2,  carbs: 35, fat: 0  },
  { id: 155, name: 'Coca-Cola (1 can)',              category: 'drinks',  kcal: 139, protein: 0,  carbs: 39, fat: 0  },
  { id: 156, name: 'Milk (1 cup full cream)',        category: 'drinks',  kcal: 149, protein: 8,  carbs: 12, fat: 8  },
  { id: 157, name: 'Soy Milk (1 cup)',               category: 'drinks',  kcal: 105, protein: 6,  carbs: 12, fat: 4  },
  { id: 158, name: 'Orange Juice (1 glass)',         category: 'drinks',  kcal: 112, protein: 2,  carbs: 26, fat: 0  },
  { id: 159, name: 'Water (1 glass)',                category: 'drinks',  kcal: 0,   protein: 0,  carbs: 0,  fat: 0  },

  // GHANAIAN FOODS
  { id: 170, name: 'Waakye (1 plate)',               category: 'carbs',   kcal: 380, protein: 14, carbs: 68, fat: 6  },
  { id: 171, name: 'Banku (small)',                  category: 'carbs',   kcal: 200, protein: 4,  carbs: 45, fat: 1  },
  { id: 172, name: 'Kenkey (1 ball)',                category: 'carbs',   kcal: 220, protein: 5,  carbs: 48, fat: 1  },
  { id: 173, name: 'Kelewele (100g)',                category: 'snacks',  kcal: 190, protein: 1,  carbs: 30, fat: 8  },
  { id: 174, name: 'Kontomire Stew (1 ladle)',       category: 'veg',     kcal: 140, protein: 5,  carbs: 8,  fat: 10 },
  { id: 175, name: 'Groundnut Soup (1 ladle)',       category: 'veg',     kcal: 250, protein: 9,  carbs: 8,  fat: 21 },
  { id: 176, name: 'Red Red / Beans Stew (1 bowl)', category: 'carbs',   kcal: 290, protein: 13, carbs: 38, fat: 10 },

  // EAST AFRICAN FOODS
  { id: 180, name: 'Ugali (1 serving)',              category: 'carbs',   kcal: 220, protein: 4,  carbs: 50, fat: 1  },
  { id: 181, name: 'Injera (1 piece)',               category: 'carbs',   kcal: 100, protein: 4,  carbs: 20, fat: 1  },
  { id: 182, name: 'Sukuma Wiki (1 serving)',        category: 'veg',     kcal: 60,  protein: 4,  carbs: 8,  fat: 2  },
  { id: 183, name: 'Doro Wat (1 serving)',           category: 'protein', kcal: 280, protein: 24, carbs: 8,  fat: 16 },
  { id: 184, name: 'Nyama Choma (100g)',             category: 'protein', kcal: 220, protein: 28, carbs: 0,  fat: 12 },
  { id: 185, name: 'Chapati (1 piece)',              category: 'carbs',   kcal: 160, protein: 4,  carbs: 28, fat: 5  },
  { id: 186, name: 'Matoke (1 serving)',             category: 'carbs',   kcal: 130, protein: 2,  carbs: 32, fat: 0  },

  // CARIBBEAN FOODS
  { id: 190, name: 'Rice and Peas (1 cup)',          category: 'carbs',   kcal: 360, protein: 10, carbs: 65, fat: 6  },
  { id: 191, name: 'Jerk Chicken (1 piece)',         category: 'protein', kcal: 270, protein: 30, carbs: 5,  fat: 14 },
  { id: 192, name: 'Ackee and Saltfish (1 serving)', category: 'protein', kcal: 290, protein: 22, carbs: 4,  fat: 20 },
  { id: 193, name: 'Curry Goat (1 serving)',         category: 'protein', kcal: 320, protein: 28, carbs: 8,  fat: 19 },
  { id: 194, name: 'Oxtail Stew (1 serving)',        category: 'protein', kcal: 380, protein: 32, carbs: 6,  fat: 24 },
  { id: 195, name: 'Roti (1 piece)',                 category: 'carbs',   kcal: 180, protein: 5,  carbs: 34, fat: 4  },
  { id: 196, name: 'Festival (1 piece)',             category: 'carbs',   kcal: 220, protein: 3,  carbs: 38, fat: 7  },

  // GLOBAL FOODS
  { id: 200, name: 'Scrambled Eggs (2 eggs)',        category: 'protein', kcal: 182, protein: 12, carbs: 2,  fat: 14 },
  { id: 201, name: 'Fried Eggs (2 eggs)',            category: 'protein', kcal: 196, protein: 12, carbs: 1,  fat: 16 },
  { id: 202, name: 'Omelette (2 eggs)',              category: 'protein', kcal: 186, protein: 12, carbs: 2,  fat: 14 },
  { id: 203, name: 'Sandwich (1 regular)',           category: 'carbs',   kcal: 320, protein: 14, carbs: 40, fat: 10 },
  { id: 204, name: 'Burger (1 regular)',             category: 'carbs',   kcal: 540, protein: 26, carbs: 45, fat: 28 },
  { id: 205, name: 'Pizza (1 slice)',                category: 'carbs',   kcal: 285, protein: 12, carbs: 36, fat: 10 },
  { id: 206, name: 'Shawarma (1 wrap)',              category: 'carbs',   kcal: 450, protein: 22, carbs: 48, fat: 18 },
  { id: 207, name: 'Spring Rolls (2 pieces)',        category: 'snacks',  kcal: 160, protein: 4,  carbs: 20, fat: 8  },
  { id: 208, name: 'Samosa (2 pieces)',              category: 'snacks',  kcal: 220, protein: 5,  carbs: 26, fat: 11 },
  { id: 209, name: 'Salad (1 bowl no dressing)',     category: 'veg',     kcal: 40,  protein: 3,  carbs: 8,  fat: 0  },
  { id: 210, name: 'Salad with dressing (1 bowl)',   category: 'veg',     kcal: 150, protein: 3,  carbs: 10, fat: 11 },
  { id: 211, name: 'Coleslaw (1 serving)',           category: 'veg',     kcal: 120, protein: 1,  carbs: 14, fat: 7  },
  { id: 212, name: 'Chips / Fries (1 serving)',      category: 'carbs',   kcal: 320, protein: 4,  carbs: 42, fat: 15 },
  { id: 213, name: 'Sausage (2 pieces)',             category: 'protein', kcal: 280, protein: 12, carbs: 2,  fat: 24 },
  { id: 214, name: 'Bacon (3 rashers)',              category: 'protein', kcal: 180, protein: 13, carbs: 0,  fat: 14 },
  { id: 215, name: 'Porridge (1 bowl)',              category: 'carbs',   kcal: 140, protein: 4,  carbs: 25, fat: 3  },
  { id: 216, name: 'Cereal with Milk (1 bowl)',      category: 'carbs',   kcal: 200, protein: 6,  carbs: 38, fat: 4  },
  { id: 217, name: 'Butter (1 tbsp)',                category: 'snacks',  kcal: 102, protein: 0,  carbs: 0,  fat: 12 },
  { id: 218, name: 'Margarine (1 tbsp)',             category: 'snacks',  kcal: 90,  protein: 0,  carbs: 0,  fat: 10 },
]
"""

# Verify clean
bad = [c for c in new_foods if ord(c) > 127]
print(f"Bad chars: {len(bad)}")

with open(r'C:\Users\mrhen\trimtrack\lib\foods.ts', 'w', encoding='utf-8') as f:
    f.write(new_foods)
print(f"Written: {len(new_foods.splitlines())} lines")